<a href="https://colab.research.google.com/github/AdityaHanwat/ofa/blob/main/R2_Sorce1_0usingLinear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression

In [ ]:
df = pd.read_csv('/content/AI_Syantheticdata - Sheet1 (1).csv')

In [ ]:
df.head()

,Soil,Crop,Variety of crop,Soil Condition,Farmer,State/Region,Market Year,Seed(KG),Temperature,Season,...,SSP(kg/acre),MOP(kg/acre),MURIATE OF POTASH(kg/acre),ZINC(kg/acre),NITROGEN(kg/acre),PHOSPHORUS(kg/acre),POTASH(kg/acre),Yield(in quantial),Price of Crop(INR/Quintal),Sales
0,Alluvial Soil,Wheat(RABI),WH 542,Excellent,F1,Gujarat,2019,45,22,winter,...,155,20,0,0,50.0,25,12,20.0,1900,38000.0
1,Black Cotton Soil,soyabean(KHARIF),SL 744,Excellent,F1,Gujarat,2019,30,30,summer,...,200,0,0,0,12.5,32,40,7.3,4929,35981.7
2,Red & Alluvial Soil,maize(KHARIF),PMH-1,Excellent,F1,Gujarat,2019,9,30,summer,...,150,0,20,8,50.0,24,12,21.0,1860,39060.0
3,Red & Alluvial Soil,maize(RABI),PMH-9,Excellent,F2,UP,2019,9,23,winter,...,150,0,20,8,70.0,24,12,32.5,1860,60450.0
4,Alluvial Soil,Wheat(RABI),PBW 752,Good,F3,Gujarat,2019,45,22,winter,...,155,20,0,0,50.0,25,12,19.2,1850,35520.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5144 entries, 0 to 5143
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Soil                        5144 non-null   object
 1   Crop                        5144 non-null   object
 2   Variety of crop             5144 non-null   object
 3   Soil Condition              5144 non-null   object
 4   Farmer                      5144 non-null   object
 5   State/Region                5144 non-null   object
 6   Market Year                 5144 non-null   int64
 7   Seed(KG)                    5144 non-null   int64
 8   Temperature                 5144 non-null   int64
 9   Season                      5144 non-null   object
 10  UREA(kg/acre)               5144 non-null   int64
 11  DAP(kg/acre)                5144 non-null   int64
 12  SSP(kg/acre)                5144 non-null   int64
 13  MOP(kg/acre)                5144 non-null   int64
 14  MURIATE OF POTASH(kg/acre)  5144 non-null   int64
 15  ZINC(kg/acre)               5144 non-null   int64
 16  NITROGEN(kg/acre)           5144 non-null   float64
 17  PHOSPHORUS(kg/acre)         5144 non-null   int64
 18  POTASH(kg/acre)             5144 non-null   int64
 19  Yield(in quantial)          5144 non-null   float64
 20  Price of Crop(INR/Quintal)  5144 non-null   int64
 21  Sales                       5144 non-null   float64
dtypes: float64(3), int64(12), object(7)
memory usage: 884.2+ KB

In [ ]:
df.isna().sum()

Soil                          0
Crop                          0
Variety of crop               0
Soil Condition                0
Farmer                        0
State/Region                  0
Market Year                   0
Seed(KG)                      0
Temperature                   0
Season                        0
UREA(kg/acre)                 0
DAP(kg/acre)                  0
SSP(kg/acre)                  0
MOP(kg/acre)                  0
MURIATE OF POTASH(kg/acre)    0
ZINC(kg/acre)                 0
NITROGEN(kg/acre)             0
PHOSPHORUS(kg/acre)           0
POTASH(kg/acre)               0
Yield(in quantial)            0
Price of Crop(INR/Quintal)    0
Sales                         0
dtype: int64

In [ ]:
df.describe()

,Market Year,Seed(KG),Temperature,UREA(kg/acre),DAP(kg/acre),SSP(kg/acre),MOP(kg/acre),MURIATE OF POTASH(kg/acre),ZINC(kg/acre),NITROGEN(kg/acre),PHOSPHORUS(kg/acre),POTASH(kg/acre),Yield(in quantial),Price of Crop(INR/Quintal),Sales
count,5144.000000,5144.000000,5144.000000,5144.000000,5144.000000,5144.000000,5144.000000,5144.000000,5144.000000,5144.000000,5144.000000,5144.000000,5144.000000,5144.00000,5144.000000
mean,2020.093507,23.250000,26.250000,100.750000,41.250000,163.750000,5.000000,10.000000,4.000000,45.625000,26.250000,19.000000,20.098834,2631.00000,43060.755482
std,0.821406,15.206329,3.766996,45.848622,23.818014,21.030299,8.661096,10.000972,4.000389,20.796778,3.345097,12.125534,8.927111,1326.95292,10118.597148
min,2019.000000,9.000000,22.000000,28.000000,0.000000,150.000000,0.000000,0.000000,0.000000,12.500000,24.000000,12.000000,7.300000,1850.00000,35520.000000
25%,2019.000000,9.000000,22.750000,89.500000,41.250000,150.000000,0.000000,0.000000,0.000000,40.625000,24.000000,12.000000,16.225000,1860.00000,35981.700000
50%,2020.000000,19.500000,26.500000,110.000000,55.000000,152.500000,0.000000,10.000000,4.000000,50.000000,24.500000,12.000000,20.500000,1860.00000,38530.000000
75%,2021.000000,33.750000,30.000000,121.250000,55.000000,166.250000,5.000000,20.000000,8.000000,55.000000,26.750000,19.000000,23.500000,2657.25000,43710.000000
max,2021.000000,45.000000,30.000000,155.000000,55.000000,200.000000,20.000000,20.000000,8.000000,70.000000,32.000000,40.000000,32.500000,4929.00000,60450.000000

In [ ]:
#Load the dataset into a pandas dataframe
df = pd.read_csv('/content/AI_Syantheticdata - Sheet1 (1).csv')

#Handle missing values
imputer = SimpleImputer(strategy='mean')
df[['Yield(in quantial)', 'Price of Crop(INR/Quintal)']] = imputer.fit_transform(df[['Yield(in quantial)', 'Price of Crop(INR/Quintal)']])

#Convert categorical variables to numerical values
le = LabelEncoder()
df['Crop'] = le.fit_transform(df['Crop'])
df['Soil'] = le.fit_transform(df['Soil'])
df['Farmer'] = le.fit_transform(df['Farmer'])
df['State/Region'] = le.fit_transform(df['State/Region'])
df['Season'] = le.fit_transform(df['Season'])
df['Variety of crop'] = le.fit_transform(df['Variety of crop'])
df['Soil Condition'] = le.fit_transform(df['Soil Condition'])

#Scale the numerical features
scaler = StandardScaler()
df[['Yield(in quantial)', 'Price of Crop(INR/Quintal)']] = scaler.fit_transform(df[['Yield(in quantial)', 'Price of Crop(INR/Quintal)']])

#Split the preprocessed data into training and testing sets
from sklearn.model_selection import train_test_split
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print(df)

      Soil  Crop  Variety of crop  Soil Condition  Farmer  State/Region  \
0        0     0                5               0       0             0
1        1     3                4               0       0             0
2        2     1                2               0       0             0
3        2     2                3               0    1111             1
4        0     0                1               1    2222             0
...    ...   ...              ...             ...     ...           ...
5139     2     2                3               0    4597             1
5140     0     0                1               1    4598             0
5141     1     3                4               0    4599             1
5142     2     1                2               0    4600             1
5143     2     2                3               0    4602             1

      Market Year  Seed(KG)  Temperature  Season  ...  SSP(kg/acre)  \
0            2019        45           22       1  ...           155
1            2019        30           30       0  ...           200
2            2019         9           30       0  ...           150
3            2019         9           23       1  ...           150
4            2019        45           22       1  ...           155
...           ...       ...          ...     ...  ...           ...
5139         2021         9           23       1  ...           150
5140         2021        45           22       1  ...           155
5141         2021        30           30       0  ...           200
5142         2021         9           30       0  ...           150
5143         2021         9           23       1  ...           150

      MOP(kg/acre)  MURIATE OF POTASH(kg/acre)  ZINC(kg/acre)  \
0               20                           0              0
1                0                           0              0
2                0                          20              8
3                0                          20              8
4               20                           0              0
...            ...                         ...            ...
5139             0                          20              8
5140            20                           0              0
5141             0                           0              0
5142             0                          20              8
5143             0                          20              8

      NITROGEN(kg/acre)  PHOSPHORUS(kg/acre)  POTASH(kg/acre)  \
0                  50.0                   25               12
1                  12.5                   32               40
2                  50.0                   24               12
3                  70.0                   24               12
4                  50.0                   25               12
...                 ...                  ...              ...
5139               70.0                   24               12
5140               50.0                   25               12
5141               12.5                   32               40
5142               50.0                   24               12
5143               70.0                   24               12

      Yield(in quantial)  Price of Crop(INR/Quintal)    Sales
0              -0.011072                   -0.550940  38000.0
1              -1.433843                    1.731955  35981.7
2               0.100957                   -0.581087  39060.0
3               1.389293                   -0.581087  60450.0
4              -0.100696                   -0.588624  35520.0
...                  ...                         ...      ...
5139            1.389293                   -0.581087  60450.0
5140           -0.100696                   -0.588624  35520.0
5141           -1.433843                    1.731955  35981.7
5142            0.100957                   -0.581087  39060.0
5143            1.389293                   -0.581087  60450.0

[5144 rows x 22 columns]

In [ ]:
#Train the model on the training data
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [ ]:
#Make predictions on the testing data
y_pred = regressor.predict(X_test)

#Calculate the performance metrics
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

print("R2 score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))

R2 score: 1.0
MAE: 1.2216396472327216e-10
MSE: 2.0533191967062472e-20